### ISSUE TITLE
TypeError encountered when recording video: Must be a real number, not NoneType

### ISSUE THREAD

**Issue by zhyuyang1023** [PJLab-ADG/DriveLikeAHuman#11]
_**Description:**_
I encountered an issue when trying to record videos in my environment using the gymnasium.wrappers. RecordVideo wrapper. I receive an error indicating that the fps value is of NoneType when the code tries to save the video. Do I need to specify a specific frame rate (fps) when initializing the environment or in the configuration?

_**Steps to Reproduce:**_
1. Initialize a 'highway-v0' environment and wrap it using gymnasium.wrappers.RecordVideo.
2. Run the environment and perform actions.
3. Try to save the video upon environment termination or reset.

**_Expected Behavior:_**
The video should save successfully without any errors.

_**Actual Behavior:**_
A TypeError is thrown indicating that the fps value is NoneType.

_**Error Logs:**_
Traceback (most recent call last):
  File "E:\DriveLikeAHuman-main\DriveLikeAHuman-main\HELLM.py", line 107, in <module>
    obs, reward, done, info, _ = env.step(output["action_id"])
  File "C:\Users\ASUS\anaconda3\lib\site-packages\gymnasium\wrappers\record_video.py", line 180, in step
    self.close_video_recorder()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\gymnasium\wrappers\record_video.py", line 193, in close_video_recorder
    self.video_recorder.close()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\gymnasium\wrappers\monitoring\video_recorder.py", line 161, in close
    clip.write_videofile(self.path, logger=moviepy_logger)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\video\VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 213, in ffmpeg_write_video
    with FFMPEG_VideoWriter(filename, clip.size, fps, codec = codec,
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 88, in __init__
    '-r', '%.02f' % fps,
TypeError: must be real number, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DriveLikeAHuman-main\DriveLikeAHuman-main\HELLM.py", line 111, in <module>
    env.close()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\gymnasium\wrappers\record_video.py", line 217, in close
    self.close_video_recorder()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\gymnasium\wrappers\record_video.py", line 193, in close_video_recorder
    self.video_recorder.close()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\gymnasium\wrappers\monitoring\video_recorder.py", line 161, in close
    clip.write_videofile(self.path, logger=moviepy_logger)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\video\VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 213, in ffmpeg_write_video
    with FFMPEG_VideoWriter(filename, clip.size, fps, codec = codec,
  File "C:\Users\ASUS\anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 88, in __init__
    '-r', '%.02f' % fps,
TypeError: must be real number, not NoneType
Moviepy - Building video E:\DriveLikeAHuman-main\DriveLikeAHuman-main\results-video\highwayv0-episode-0.mp4.
Moviepy - Writing video E:\DriveLikeAHuman-main\DriveLikeAHuman-main\results-video\highwayv0-episode-0.mp4

Moviepy - Building video E:\DriveLikeAHuman-main\DriveLikeAHuman-main\results-video\highwayv0-episode-0.mp4.
Moviepy - Writing video E:\DriveLikeAHuman-main\DriveLikeAHuman-main\results-video\highwayv0-episode-0.mp4

C:\Users\ASUS\anaconda3\lib\site-packages\gymnasium\wrappers\monitoring\video_recorder.py:182: UserWarning: WARN: Unable to save last video! Did you call close()?

_**Environment:**_
OS: [Windows 11]
Python Version: [3.10.13]
gymnasium version: [0.29.1]
moviepy version: [1.0.3]
IDE: [PyCharm 2023.2.1 (Professional Edition)]

**Comment by zijinoier** [comment]
hmmm... I'm not sure. Since I used Ubuntu to develop and test and I didn't encounter similar questions before. 
My environment are:
```
gymnasium            0.28.1
moviepy                 1.0.3
Python                   3.8.16
```

Hope this can help!

**Comment by Daniel-xsy** [comment]
This might be the compatible issue between `moviepy` and `decorator`. This solved my problem:
```bash
pip uninstall moviepy decorator
pip install moviepy
```
Refer to https://github.com/Zulko/moviepy/issues/1625#issuecomment-973056577
